version: '3.7'
services:
  db:
    image: mysql:latest
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_DATABASE: my_resto
      MYSQL_USER: myresto
      MYSQL_PASSWORD: myresto
      MYSQL_ROOT_PASSWORD: myresto
    volumes:
      - ./db-data:/var/lib/mysql
    networks:
      - spring-boot-app-network
  spring-boot-app:
    container_name: spring-apps
    image: thomaslpro/myresto
    pull: true
    depends_on:
      - db
    ports:
      - 80:8080
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    networks:
      - spring-boot-app-network

networks:
  spring-boot-app-network:
    name: spring-boot-app-network
    driver: bridge
