version: '3.7'
services:
  db:
    image: mysql:latest
    container_name: db
    ports: 
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: my_resto
      MYSQL_USER: my_resto
      MYSQL_PASSWORD: my_resto
      MYSQL_ROOT_PASSWORD: my_resto
    volumes:
      - persistent:/var/lib/mysql
    networks:
      - spring-boot-app-network
  spring-boot-app:
    container_name: spring-apps
    image: thomaslpro/myresto
    depends_on:
      - db
    ports:
      - 80:8080
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    networks:
      - spring-boot-app-network
volumes:
    persistent:
networks:
  spring-boot-app-network:
    name: spring-boot-app-network
    driver: bridge
